"""empty message

Revision ID: 15c1627892ea
Revises: 
Create Date: 2024-08-19 17:43:39.035893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15c1627892ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('imagen_perfil',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
