"""empty message

Revision ID: 9e35b2cfaa2f
Revises: b1f1012f56c7
Create Date: 2024-08-20 13:09:48.167930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e35b2cfaa2f'
down_revision = 'b1f1012f56c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
