"""empty message

Revision ID: b1f1012f56c7
Revises: 15c1627892ea
Create Date: 2024-08-20 09:36:23.938535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1f1012f56c7'
down_revision = '15c1627892ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=20), nullable=False))
        batch_op.drop_column('imagen_perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_perfil', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('avatar')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
