"""empty message

Revision ID: e46e04a0decb
Revises: 
Create Date: 2024-08-23 11:28:41.923759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46e04a0decb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('atributos', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('apellido', sa.String(length=20), nullable=True),
    sa.Column('apellido2', sa.String(length=20), nullable=True),
    sa.Column('residencia', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('telefonoE', sa.String(length=15), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('confirmpassword', sa.String(length=60), nullable=False),
    sa.Column('alergias', sa.String(length=100), nullable=True),
    sa.Column('tiposangre', sa.String(length=100), nullable=True),
    sa.Column('cronico', sa.String(length=100), nullable=True),
    sa.Column('medicamentos', sa.String(length=100), nullable=True),
    sa.Column('nacimiento', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.Column('usuario', sa.Text(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multimedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Text(), nullable=False),
    sa.Column('usuario', sa.Text(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('kilometros', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('lugar', sa.Text(), nullable=True),
    sa.Column('finaliza', sa.Text(), nullable=True),
    sa.Column('etapa', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('hora', sa.Integer(), nullable=True),
    sa.Column('salida', sa.Text(), nullable=True),
    sa.Column('dificultad', sa.Text(), nullable=True),
    sa.Column('sinpe', sa.Integer(), nullable=True),
    sa.Column('coordinador', sa.Text(), nullable=True),
    sa.Column('precio', sa.Text(), nullable=True),
    sa.Column('limite_pago', sa.DateTime(), nullable=True),
    sa.Column('parqueo', sa.Text(), nullable=True),
    sa.Column('mascotas', sa.Text(), nullable=True),
    sa.Column('duchas', sa.Text(), nullable=True),
    sa.Column('banos', sa.Text(), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('multimedia')
    op.drop_table('imagenes')
    op.drop_table('user')
    op.drop_table('tags')
    # ### end Alembic commands ###
